
baseURL: "https://bollenstreekdigitaal.nl/"
languageCode: "nl-nl"
title: "Digitale Transformatie met AI"
theme: "papermod"
params:
  author: "Wijnand Baretta"
  description: "Ik help MKB-bedrijven slimmer werken met AI en technologie."
  defaultTheme: "light"
  showCodeCopyButtons: true
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Over mij
      url: /about/
      weight: 2
    - name: Diensten
      url: /services/
      weight: 3
    - name: Blog
      url: /blog/
      weight: 4
    - name: Contact
      url: /contact/
      weight: 5
